Maker.create(name: "Apple Co")
Maker.create(name: "Oppo")
Mobile.create(name: "iPhone 8 Plus 256GB", ram: "2GB", price: 1000000, colors_attributes: [{color: "pink"}, {color: "black"}, {color: "white"}], width: "78.1 mm", height: "158.4 mm", font_camera: "12 MP" , behind_camera: "12 MP", weight: 202, battery: "2691 mAh", resolution_width: 1080, resolution_height: 1920, maker_id: 1, cover_image: "p-1.jpg", description: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.")
Mobile.create(name: "iPSamsung 8 Plus 256GB", ram: "3GB", price: 1000000, colors_attributes: [{color: "pink"}, {color: "black"}, {color: "white"}], width: "78.1 mm", height: "158.4 mm", font_camera: "12 MP" , behind_camera: "12 MP", weight: 202, battery: "2691 mAh", resolution_width: 1080, resolution_height: 1920, maker_id: 1, cover_image: "p-1.jpg", description: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.")
Mobile.create(name: "iPhone 6 Plus 256GB", ram: "2GB", price: 1200000, colors_attributes: [{color: "pink"}, {color: "black"}, {color: "white"}], width: "78.1 mm", height: "158.4 mm", font_camera: "12 MP" , behind_camera: "12 MP", weight: 202, battery: "2691 mAh", resolution_width: 1080, resolution_height: 1920, maker_id: 1, cover_image: "p-1.jpg", description: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.")
Mobile.create(name: "iPhone 7 Plus 256GB", ram: "2GB", price: 1100000, colors_attributes: [{color: "pink"}, {color: "black"}, {color: "white"}], width: "78.1 mm", height: "158.4 mm", font_camera: "12 MP" , behind_camera: "12 MP", weight: 202, battery: "2691 mAh", resolution_width: 1080, resolution_height: 1920, maker_id: 1, cover_image: "p-1.jpg", description: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.")
Mobile.create(name: "iPhone 4 Plus", ram: "2GB", price: 900000, colors_attributes: [{color: "pink"}, {color: "black"}, {color: "white"}], width: "78.1 mm", height: "158.4 mm", font_camera: "12 MP" , behind_camera: "12 MP", weight: 202, battery: "2691 mAh", resolution_width: 1080, resolution_height: 1920, maker_id: 1, cover_image: "p-1.jpg", description: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.")

Mobile.create(name: "Oppo Neo 3", ram: "2GB", price: 1500000, colors_attributes: [{color: "pink"}, {color: "black"}, {color: "white"}], width: "78.1 mm", height: "158.4 mm", font_camera: "12 MP" , behind_camera: "12 MP", weight: 202, battery: "2691 mAh", resolution_width: 1080, resolution_height: 1920, maker_id: 2, cover_image: "p-1.jpg", description: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.")
Mobile.create(name: "Oppo Neo 4", ram: "2GB", price: 1400000, colors_attributes: [{color: "pink"}, {color: "black"}, {color: "white"}], width: "78.1 mm", height: "158.4 mm", font_camera: "12 MP" , behind_camera: "12 MP", weight: 202, battery: "2691 mAh", resolution_width: 1080, resolution_height: 1920, maker_id: 2, cover_image: "p-1.jpg", description: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.")
Mobile.create(name: "Oppo Neo 5", ram: "2GB", price: 1300000, colors_attributes: [{color: "pink"}, {color: "black"}, {color: "white"}], width: "78.1 mm", height: "158.4 mm", font_camera: "12 MP" , behind_camera: "12 MP", weight: 202, battery: "2691 mAh", resolution_width: 1080, resolution_height: 1920, maker_id: 2, cover_image: "p-1.jpg", description: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.")
Mobile.create(name: "Oppo Neo 6", ram: "2GB", price: 1200000, colors_attributes: [{color: "pink"}, {color: "black"}, {color: "white"}], width: "78.1 mm", height: "158.4 mm", font_camera: "12 MP" , behind_camera: "12 MP", weight: 202, battery: "2691 mAh", resolution_width: 1080, resolution_height: 1920, maker_id: 2, cover_image: "p-1.jpg", description: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.")
Mobile.create(name: "Oppo Neo 7", ram: "2GB", price: 1100000, colors_attributes: [{color: "pink"}, {color: "black"}, {color: "white"}], width: "78.1 mm", height: "158.4 mm", font_camera: "12 MP" , behind_camera: "12 MP", weight: 202, battery: "2691 mAh", resolution_width: 1080, resolution_height: 1920, maker_id: 2, cover_image: "p-1.jpg", description: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.")

# Maker.create(name: "Apple Co");
# 8.times do
#     Mobile.create(name: "iPhone 8 Plus 256GB", price: 250, width: 78, height: 158, font_camera: 12 , 
#       behind_camera: 12, weight: 202, battery: 2691, resolution_width: 1080, resolution_height: 1920, 
#         maker_id: 1, cover_image: "p-1.jpg", colors_attributes: [{color: "pink"}, {color: "black"}, {color: "white"}]);
# end
